name: Packaging and test

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build-sdist:
    name: 🧑‍🍳 sdist
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [ "11" ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.${{ matrix.python-version }}"

      - run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python setup.py sdist

      - uses: actions/upload-artifact@v4
        with:
          name: setuptools_rust_bundled_sdist
          path: dist/*
          if-no-files-found: error
          overwrite: true

  test-sdist:
    name: 📋 sdist
    needs: [build-sdist]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: ["ubuntu-latest", "macos-13", "macos-latest", "windows-latest"]
        os: ["ubuntu-latest"]
        python-version: [ "11" ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.${{ matrix.python-version }}"

      - uses: actions/download-artifact@v4
        with:
          name: setuptools_rust_bundled_sdist
          path: dist

      - run: |
          yes | rustup self uninstall || true
          python -m pip install -vvv dist/*
          python -m pip install -vvv example
          rm -rf example
          python -c "import example"
